#
# Normalization Rules for Preprocessing
#

FACILITY_NAME_OUTLIERS = [
    "-", "SAMPING & BELAKANG", "LISTRIK", "ATAP BAJA", "ROW JALAN",
    'BUILT IN ROBES', "R.TAMU", "STUDY", "BATH", "R. MAKAN", "SERTIFIKAT",
    "HADAP", "DEKAT", "CLOSE TO", "PROMO", "CAFE", "PET F", "BONUS", "SOFA",
    "DLL", "KURSI", "VIEW", "PINTU TOL", "STRATEGIS", "NEGO", "PAVILLION", "TV",
    "MASIH ADA", "TOKEN", "POLISHED", "KAWASAN", "LENGKAP", "ASRI", "HYPERMART",
    "POSISI", "SMOKING", "RUANG", "CLUB", "SEPARATE", "CEILING", "GROUND FLOOR",
    "SPRING BED", "MEJA"
]

FACILITY_NAME_RULESET = {
    "JET PUMP": "AIR TANAH",
    "PAM": "AIR PAM",
    "PARKIR": "PARKIR",
    "PARKING": "PARKIR",
    "GARASI": "GARASI",
    "CARPORT": "CARPORT",
    "CARPOT": "CARPORT",
    "AC": "AC",
    "AIR COND": "AC",
    "AIRCON": "AC",
    "HEATING": "HEATING",
    # places
    "AULA": "AULA",
    "LOUNGE": "AULA",
    # security
    "SECURITY": "KEAMANAN",
    "KEAMANAN": "KEAMANAN",
    "SMART DOOR": "KEAMANAN",
    "ALARM SYSTEM": "KEAMANAN",
    # outdoor
    "SPA": "HALAMAN",
    "BBQ": "HALAMAN",
    "DECK": "HALAMAN",
    "COURTYARDS": "HALAMAN",
    "HALAMAN": "HALAMAN",
    "TERAS": "HALAMAN",
    "KEBUN": "HALAMAN",
    "TAMAN": "TAMAN",
    "GARDEN": "TAMAN",
    "BERMAIN": "TAMAN",
    "ENTERTAINING": "TAMAN",
    "KIDS PARK": "TAMAN",
    "PLAYGR": "PLAYGROUND",
    "PLAY GROUND": "PLAYGROUND",
    "LAPANGAN BERMAIN": "PLAYGROUND",
    "KOI": "KOLAM IKAN",
    "KOLAM PANCING": "KOLAM IKAN",
    # sports
    "GYM": "GYM",
    "SWIMMING POOL": "KOLAM RENANG",
    "POOL INGROUND": "KOLAM RENANG",
    "JOGGING TRACK": "TRACK LARI",
    "LAPANGAN": "LAPANGAN",
    "FUTSAL": "LAPANGAN",
    # kitchen
    "KITCHEN": "DAPUR",
    "KOMPOR": "DAPUR",
    "KULKAS": "DAPUR",
    "JEMURAN": "LAUNDRY",
    "LAUNDRY": "LAUNDRY",
    "CUCI": "LAUNDRY",
    "PEMANAS AIR": "WATER HEATER",
    "HOT WATER": "WATER HEATER",
    "WATER HEATER": "WATER HEATER",
    "GAS": "GAS",
    # internet
    "INTERNET": "INTERNET",
    "WIFI": "INTERNET",
    "WI-FI": "INTERNET",
    "BROADBAND": "INTERNET",
    # pray
    "MASJID": "MASJID",
    "MUSHOLA": "MUSHOLLA",
}

COMPANY_NAME_COMMONS = [
    "BRIGHTON", "RAY WHITE", "LJ HOOKER", "XAVIER MARKS", "MR REALTY",
    "ERA FIESTA", "ASIA ONE", "RE/MAX", "ERA PROJECT", "ERA VICTORIA", "MPRO",
    "9 PRO", "58 PRO", "ATLANTIS", "BEE", "BEYOND PROPERTI", "BINTANG PROPERTI",
    "BUANA REALTY", "VISION PROPERTI", "SUNRISE", "KUNCI REALTY", "HARCOURTS",
    "GADING PRO", "EXIST", "ERA STAR", "ERA SKY", "DISCOVERY", "DREAM HOME",
    "EAGLE TREE", "ERA", "INDOHOUSE", "JPI", "MITRA PROPERTI", "MYPRO",
    "ONE REALTY", "PJ PRO", "PROFESIONAL BROKER", "PROMEX", "PROPNEX",
    "SUCCESS PROPERTI", "TUNGGADEWI LAND"
]

COMPANY_NAME_STOPWORDS = [
    "DEPOK", "TANGGERANG", "BANDUNG", "JAKARTA", "GARDEN CITY",
    "GADING SERPONG", "KELAPA GADING", "CILEUNGSI", "CENGKARENG", "BINTARO",
    "MALANG", "TANGERANG", "CIBUBUR", "PALEMBANG", "TANJUNG DUREN", "SENTUL",
    "JATIASIH", "BRANCH", "AGENCY", "INTERIOR DESIGN", "&"
]

COMPANY_NAME_INDEPENDENT = [
    "NOT IDENTIFIED", "INDEPDENDENT", "INDEPEDENT", "INDEPENDENT"
]
