services:
  mariadb:
    image: mariadb:11.3.2
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: rumah_bogor
      MARIADB_USER: kucingmenangis
      MARIADB_PASSWORD: i32F8H4kqY
      MARIADB_ROOT_PASSWORD: Gyc5Qpfz2tq3

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots

  web:
    build: app
    ports:
      - 80:8000
    environment:
      DEBUG: false

      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: kucingmenangis
      DB_PASSWORD: i32F8H4kqY
      DB_NAME: rumah_bogor

      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_GRP_PORT: 6334
      QDRANT_INDEX_NAME: rumah_bogor
      QDRANT_INDEX_DIM: 1536
      QDRANT_HNSW_M: 16
      QDRANT_HNSW_EF: 100


volumes:
  mariadb:
  qdrant-storage:
  qdrant-snapshots:
