services:
  postgres:
    image: paradedb/paradedb:latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - docker/db.env

  web:
    build: src/streamlit-rumah
    ports:
      - 443:8000
    depends_on:
      - postgres
    volumes:
      - docker/streamlit-secrets.toml:/usr/src/app/.streamlit/secrets.toml

  mcp:
    build: src/mcp-rumah
    ports:
      - 443:8000
    depends_on:
      - postgres
    env_file:
      - docker/mcp.env

volumes:
  postgres:
