services:
  mariadb:
    image: mariadb:11.3.2
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - mariadb.env

  qdrant:
    image: qdrant/qdrant:v1.9.1
    restart: unless-stopped
    ports:
      - 8001:6333
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots

  web:
    image: fahminlb33/project-rumah-regresi:1.0.0
    restart: unless-stopped
    ports:
      - 443:8000
    depends_on:
      - mariadb
      - qdrant
    env_file:
      - web.env
    volumes:
      - ./uploads:/opt/uploads
      - ./ssl:/etc/ssl
      - ./cache:/opt/cache
      - ./models:/opt/models

volumes:
  mariadb:
  qdrant-storage:
  qdrant-snapshots:
