services:
  mariadb:
    image: mariadb:11.3.2
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - docker/mariadb.env

  qdrant:
    image: qdrant/qdrant:v1.7.3
    restart: unless-stopped
    ports:
      - 8001:6333
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots

  web:
    image: fahminlb33/bogor-house-price:latest
    restart: unless-stopped
    ports:
      - 80:8000
    depends_on:
      - mariadb
      - qdrant
    env_file:
      - docker/web.env

volumes:
  mariadb:
  qdrant-storage:
  qdrant-snapshots:
