services:
  mariadb:
    image: mariadb:11.3.2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker:/docker-entrypoint-initdb.d
    env_file:
      - docker/mariadb.env

  qdrant:
    image: qdrant/qdrant:v1.7.3
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots

  web:
    build: app
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - mariadb
      - qdrant
    env_file:
      - docker/web.env

  docs:
    build: app_docs
    restart: always
    ports:
      - 8002:8000

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
      - docs

volumes:
  mariadb:
  qdrant-storage:
  qdrant-snapshots:
