services:
  mariadb:
    image: mariadb:11.3.2
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - docker/mariadb.env

  qdrant:
    image: qdrant/qdrant:v1.7.3
    restart: unless-stopped
    ports:
      - 8001:6333
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots

  docs:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./app_docs:/usr/share/nginx/html

  web:
    build: app
    restart: unless-stopped
    ports:
      - 8003:8000
    depends_on:
      - mariadb
      - qdrant
    env_file:
      - docker/web.env

  image_proxy:
    image: python:3.11.8-slim
    restart: unless-stopped
    ports:
      - 8004:8080
    volumes:
      - ./docker/reverse_proxy.py:/usr/src/app/reverse_proxy.py
    command: python /usr/src/app/reverse_proxy.py
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/proxy.conf:/etc/nginx/proxy.conf

volumes:
  mariadb:
  qdrant-storage:
  qdrant-snapshots:
