services:
  postgres:
    image: paradedb/paradedb:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - docker/db.env

  # web:
  #   build: src/streamlit-rumah
  #   restart: unless-stopped
  #   ports:
  #     - 443:8000
  #   depends_on:
  #     - mariadb
  #     - qdrant
  #   env_file:
  #     - docker/web.env
  #   volumes:
  #     - ./docker/uploads:/opt/uploads

volumes:
  postgres:
