version: 2

macros:
  # ---- normalize_values.sql
  - name: bool_to_int
    description: A macro to convert boolean columns to integer, designed to use on SELECT queries
    arguments:
      - name: column_name
        type: string
        description: Column name to convert to integer

  - name: normalize_kondisi
    description: A macro to normalize the values of `kondisi_properti` and `kondisi_perabotan` column, designed to use on SELECT queries
    arguments:
      - name: column_name
        type: string
        description: Column name to normalize the values

  - name: normalize_sertifikat
    description: A macro to normalize the values of `sertifikat`, designed to use on SELECT queries
    arguments:
      - name: column_name
        type: string
        description: Column name to normalize the values

