name: 'rumah_transform'
version: '1.0.0'
config-version: 2

profile: 'rumah_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  rumah_transform:
    staging:
      +materialized: table
    intermediate:
      +materialized: view
    marts:
      +materialized: view
