rumah_transform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../dataset/rumah.duckdb'
      external_root: '../dataset/curated'
      extensions:
        - httpfs
        - parquet
      module_paths:
        - plugins
      plugins:
        - module: rumah_plugin
